numero = int(input("Digite um número: "))
print("O número escolhido é {}.".format(numero))
print("O dobro desse número é {}".format(numero * 2))
print("O triplo desse número é {}".format(numero * 3))
print("A raiz quadrada desse número é {}".format(numero ** (1/2)))
